#!/usr/bin/env bash

if [[ -z $DROPLET_2_IP ]]; then
  echo "Enviroment variable missing: DROPLET_2_IP"
  exit 1
fi

if [[ -z $DROPLET_2_USER ]]; then
  echo "Enviroment variable missing: DROPLET_2_USER"
  exit 1
fi

rsync -av ./_site/ $DROPLET_2_USER@$DROPLET_2_IP:~/www/jacksondean.net/public/
